defaultSemverRangePrefix: ""

enableGlobalCache: true

nmMode: hardlinks-local

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

preferAggregateCacheInfo: true

yarnPath: .yarn/releases/yarn-3.0.2.cjs
