version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:13
    working_directory: ~/app

jobs:
  checkout_code:
    executor: node
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/app
          paths:
            - ./*

  dependencies:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install NPM dependencies
          command: yarn install --frozen-lockfile
      - persist_to_workspace:
          root: ~/app
          paths:
            - node_modules

  build:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: yarn run build

  test:
    executor: node
    docker:
      - image: circleci/node:13
      - image: circleci/postgres:11-alpine
    environment:
      JEST_JUNIT_OUTPUT_DIR: '../../test-results/test'
      NODE_ENV: 'test'
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: yarn run test:ci
      - run:
          name: Send coverage report
          command: cat coverage/lcov.info | yarn coveralls
      - store_test_results:
          when: always
          path: test-results

  lint:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: yarn run lint -f junit -o ../../test-results/lint/results.xml
      - store_test_results:
          when: always
          path: test-results

workflows:
  version: 2
  build_test_lint:
    jobs:
      - checkout_code
      - dependencies:
          requires:
            - checkout_code
      - build:
          requires:
            - dependencies
      - test:
          requires:
            - dependencies
      - lint:
          requires:
            - dependencies
