version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:13
    working_directory: ~/app
    environment:
      JEST_JUNIT_OUTPUT_NAME: 'results.xml'
      JEST_JUNIT_ANCESTOR_SEPARATOR: ' > '

jobs:
  checkout_code:
    executor: node
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/app
          paths:
            - ./*

  dependencies:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install NPM dependencies
          command: yarn install --frozen-lockfile
      - persist_to_workspace:
          root: ~/app
          paths:
            - node_modules

  build:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: yarn run build

  test:
    executor: node
    docker:
      - image: circleci/node:13
      - image: circleci/postgres:11-alpine
    environment:
      JEST_JUNIT_OUTPUT_DIR: './test-results/test'
      NODE_ENV: 'test'
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: yarn run test --ci --reporters=jest-junit --reporters=default
      - store_test_results:
          when: always
          path: test-results

  lint:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: yarn run lint -f junit -o ./test-results/lint/results.xml
      - store_test_results:
          when: always
          path: test-results

  breaking_changes:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Check for changes in schema
          command: npx @graphql-inspector/cli diff git:origin/master:src/graphql/snapshot.graphql src/graphql/snapshot.graphql

  deploy:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - '82:ad:32:dd:dc:e7:47:d9:7c:e9:d4:77:8b:06:4b:87'
      - run:
          name: Trust server host
          command: echo "|1|+DMvKJQrt7hMh3kgeAXrlIbp1rk=|MaXNHnRb4SDKMDV+h2gz/6CNt+8= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBGoaaGESTE5v5dfHtwXLW5vpx4cjJvHkbhyqORu0Ru0OXZfAKFfq3HS2RDpiJCptgUfuH6D5ppurO3D1ar5240Q=" >> ~/.ssh/known_hosts
      - run:
          name: Deploy to Dokku
          command: git push dokku@142.93.167.243:siege

workflows:
  version: 2
  build_test_lint:
    jobs:
      - checkout_code
      - dependencies:
          requires:
            - checkout_code
      - build:
          requires:
            - dependencies
      #- test:
      #    requires:
      #      - dependencies
      - lint:
          requires:
            - dependencies
      - breaking_changes:
          requires:
            - lint
            - build
            #- test
      - deploy:
          requires:
            - breaking_changes
          filters:
            branches:
              only: master
