name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - ".gitignore"
      - ".github/**"
      - "!.github/workflows/*.yml"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - ".gitignore"
      - ".github/**"
      - "!.github/workflows/*.yml"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - run: yarn lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - run: yarn test

  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - run: yarn typecheck
